// Top-level build file for all modules

buildscript {
    dependencies {
        // Only keep google-services here
        classpath 'com.google.gms:google-services:4.4.2'
    }
}

plugins {
    id "com.android.application" version "8.1.4" apply false
    id "org.jetbrains.kotlin.android" version "1.9.22" apply false
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}